	[[module.entry]]
	name = "KDTEST"
	uuid = UUIDREG_STR_KEYWORD
	affinity_mask = "0x1"
	instance_count = "1"
	domain_types = "0"
	load_type = "0"
	module_type = "8"
	auto_start = "0"
	sched_caps = [1, 0x00008000]

	REM # pin = [dir, type, sample rate, size, container, channel-cfg]
	pin = [0, 0, 0xfeef, 0xf, 0xf, 0x45ff,
			1, 0, 0xfeef, 0xf, 0xa, 0x45ff]

	REM # mod_cfg [PAR_0 PAR_1 PAR_2 PAR_3 IS_BYTES CPS IBS OBS MOD_FLAGS CPC OBLS]
	mod_cfg = [0, 0, 0, 0, 480, 1114000, 64, 64, 0, 0, 0]

	index = __COUNTER__
