#ifndef LOAD_TYPE
#define LOAD_TYPE "0"
#endif

	[[module.entry]]
	name = "PROBE"
	uuid = UUIDREG_STR_PROBE4
	affinity_mask = "0x1"
	instance_count = "1"
	domain_types = "0"
	load_type = LOAD_TYPE
	module_type = "9"
	auto_start = "0"
	sched_caps = [1, 0x00008000]

	REM # mod_cfg [PAR_0 PAR_1 PAR_2 PAR_3 IS_BYTES CPS IBS OBS MOD_FLAGS CPC OBLS]
	mod_cfg = [0, 0, 0, 0, 4096, 100000, 48, 48, 0, 1000, 0]

	index = __COUNTER__
